### ISSUE TITLE
Stardust 1.5.0 | 1.20.2

### ISSUE THREAD

**Issue by pixo2000** [0xTas/stardust#2]
Hi, i saw that the new version has 1.20.1 and 1.20.4 support... i only play 1.20.2. would it be hard do "reupdate"?

**Comment by 0xTas** [comment]
It wouldn't be "hard", but I don't have any plans to support 1.20.2. You could clone one of the branches and upgrade or downgrade it yourself (plenty of tutorials online for that,) but the code for MusicTweaks had to change a lot between 1.20.1 & 1.20.4.
It's a 50/50 gamble whether 1.20.1 or 1.20.4 would be the proper branch to start with, in order to avoid having to re-do all the changes that I had to make to that module.

**Comment by pixo2000** [comment]
Just deleted the MusicTweaks lol
