### ISSUE TITLE
Idea: AutoDoors

### ISSUE THREAD

**Issue by pixo2000** [0xTas/stardust#4]
Could you add a mode for trapdoors and/or Fence Gates?

**Comment by 0xTas** [comment]
Fence gates: probably yes.

Trapdoors already kinda work (there's an option for it) but it isn't fully functional because PlayerMoveEvents don't fire when going up/down ladders. So for now it only opens/closes trapdoors when you aren't on a ladder. I might fix that eventually, but with 2b2t recently updating again I've got more important things to work on for now.

**Comment by 0xTas** [comment]
This has been added in https://github.com/0xTas/stardust/commit/bfadec2ec8645990c4cb65000fd47a2993b286ec.
