### ISSUE TITLE
Could you make a 1.21 fork? would appreciate it :)

### ISSUE THREAD

**Issue by Lexion242** [0xTas/stardust#7]

**Comment by 0xTas** [comment]
The [1.21.1](https://github.com/0xTas/stardust/tree/1.21.1) branch is in active development, you can download the prerelease builds for that [here](https://github.com/0xTas/stardust/releases/tag/latest-1.21.1).

It will be merged into the main branch and a full release published after 2b2t updates.

**Comment by Lexion242** [comment]
yeah i know, but specifically 1.21.

**Comment by 0xTas** [comment]
I'd prefer if the 1.21.1 branch supported both versions, so let me look into that first when I get a chance.

**Comment by 0xTas** [comment]
This isn't going to be practical. Meteor itself doesn't even support 1.21 unless you build it from a past commit, and at that point you may as well just open the jar file with something like 7zip & change "1.21" to "1.21.1" in the fabric-mod.json file for whatever mods you use which haven't updated yet. Afaik, 1.21.1 has no breaking changes on the client, so just change the version number in fabric-mod.json and it will run perfectly fine.

**Comment by 0xTas** [comment]
Meteor added dual support for 1.21 in https://github.com/MeteorDevelopment/meteor-client/commit/262e5f3a98c9ef64151f31a1b0fc9fd97e3d3083 which you can benefit from by downloading the newest dev-build.
Because of this, I went ahead and added 1.21 support to Stardust (https://github.com/0xTas/stardust/commit/64a0e70e7b99494104110a3a1d5341528a575a53), which you can also get with the [newest dev-builds](https://github.com/0xTas/stardust/releases/tag/latest-1.21.1).
